#!/bin/bash
#SBATCH --job-name=vis_desktop
env | grep SLURM
echo " Starting CSD3 desktop..."
echo " Setting up the system environment..."
# This is required for tcsh desktops to work
source /etc/profile.d/modules.sh
module purge
module load slurm
module load turbovnc
module list

rm /tmp/.X1-lock
echo " Starting VNC..."
vncserver :1 -otp -novncauth
vncserver -list

#Wait for things to die
while true;
do
    sleep 30;
done

